# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8935af32f5b005c391546860c6008a2c05627f006c7d86dd118dddb27fc0e766e312c088202eb2af25ac428fc0b450b9e515c4d287728c1d158613d396bf6127

test:
  secret_key_base: f193cfb13593de23063dcc0a77bebf57b42364972d2a9f3a2d615b233d9124b97bff4a72e58b11a84daa8e97052c1836ac2c18b474510ac56ab2a1faf4049873

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
